### ISSUE TITLE
Determine set pruning window extrinsic weight

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/chainlink-polkadot#15]
the `set_pruning_window` extrinsic doesn't have a benchmark and weights yet.
Because the extrinsic is dependent on the diff `pruning_window` - `feed.pruning_window` we should look into how to determine this dependent on the given parameter. 

Related: https://github.com/smartcontractkit/chainlink-polkadot/blob/master/pallet-chainlink-feed/src/lib.rs#L717

**Comment by clearloop** [comment]
Didn't notice this in #12 LOL, I'll implement this, ref #6

**Comment by dutterbutter** [comment]
re: https://github.com/paritytech/bench-bot
