### ISSUE TITLE
Equivalence with FluxAggregator contract

### ISSUE THREAD

**Issue by dutterbutter** [ChainSafe/chainlink-polkadot#4]
### Task Description

Analyze whether the functions are equivalent to the contract: Are there any missing features?

[FluxAggregator contract](https://github.com/smartcontractkit/chainlink/blob/dabada25f5dd7bbc49a76ed1d172a83083cdd8f0/evm-contracts/src/v0.6/FluxAggregator.sol)

**Comment by mattsse** [comment]
In #1 The `FeedInterface` trait was extended to get access to the configured `decimals` of the feed:
https://github.com/ChainSafe/chainlink-polkadot/blob/main/pallet-chainlink-feed/src/lib.rs#L235-L236
After comparing them, a substrate `Feed` is more or less equal to a solidity `FluxAggregator`, no features are missing as far as I can tell.

Vote to close.
