### ISSUE TITLE
Automated storage pruning

### ISSUE THREAD

**Issue by dutterbutter** [ChainSafe/chainlink-polkadot#7]
### Task Description 

- Currently storage pruning is only executed after an admin manually calls prune and uses a fixed pruning window.
- The pruning window should be customisable (on a per feed basis?) that also specifies the number of rounds to keep around.
- Prune should be called automatically (hooks)

**Comment by mattsse** [comment]
After checking the existing [prune](https://github.com/ChainSafe/chainlink-polkadot/blob/main/pallet-chainlink-feed/src/lib.rs#L809) function, my suggestion would be to move the logic into a hook to prune automatically every other block or so, this will eventually require an additional mapping to keep track of the feeds to prune.
